# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# PipeLines > Stages > Jobs > Tasks(Steps)

jobs:
- job: Job1
  steps:
  - script: echo Job 1!
    displayName: 'Run a one-line script change'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  dependsOn: Job1
  steps:
  - script: echo Job 2!
    displayName: 'Run a one-line script change Job 2'
- job: Job3
  dependsOn: Job2
  steps:
  - script: echo Job 3!
    displayName: 'Run a one-line script change Job 2'
